# Generated by Django 5.2.16 on 2026-07-27 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NettingWindow',
            fields=[
                ('window_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('gross_obligation_count', models.IntegerField()),
                ('net_obligation_count', models.IntegerField()),
                ('net_volume', models.DecimalField(decimal_places=2, max_digits=18)),
                ('liquidity_saved', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('tx_id', models.UUIDField(primary_key=True, serialize=False)),
                ('payer', models.CharField(max_length=50)),
                ('payee', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('netted', 'Netted'), ('settled', 'Settled'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('netting_window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='obligations.nettingwindow')),
            ],
            options={
                'indexes': [models.Index(fields=['payer', 'payee', 'timestamp', 'status'], name='obligations_payer_a29f0f_idx')],
            },
        ),
    ]
