# Generated by Django 5.2.16 on 2026-08-11 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=50)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'net position',
                'verbose_name_plural': 'net positions',
            },
        ),
        migrations.CreateModel(
            name='ParticipantBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=50, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'participant balance',
                'verbose_name_plural': 'participant balances',
            },
        ),
        migrations.CreateModel(
            name='SettlementAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=50)),
                ('payee', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('settled', 'Settled'), ('failed', 'Failed')], max_length=20)),
                ('attempt_number', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'settlement attempt',
                'verbose_name_plural': 'settlement attempts',
            },
        ),
        migrations.AlterModelOptions(
            name='nettingwindow',
            options={'ordering': ['-end_time'], 'verbose_name': 'netting window', 'verbose_name_plural': 'netting windows'},
        ),
        migrations.AlterModelOptions(
            name='obligation',
            options={'verbose_name': 'obligation', 'verbose_name_plural': 'obligations'},
        ),
        migrations.AlterField(
            model_name='obligation',
            name='netting_window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligations', to='obligations.nettingwindow'),
        ),
        migrations.AddIndex(
            model_name='nettingwindow',
            index=models.Index(fields=['end_time'], name='obligations_end_tim_8be27b_idx'),
        ),
        migrations.AddField(
            model_name='netposition',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_positions', to='obligations.nettingwindow'),
        ),
        migrations.AddIndex(
            model_name='participantbalance',
            index=models.Index(fields=['participant'], name='obligations_partici_73652e_idx'),
        ),
        migrations.AddField(
            model_name='settlementattempt',
            name='window',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_attempts', to='obligations.nettingwindow'),
        ),
        migrations.AddConstraint(
            model_name='netposition',
            constraint=models.UniqueConstraint(fields=('window', 'participant'), name='unique_window_participant'),
        ),
    ]
