# Generated by Django 5.2.16 on 2026-08-14 13:04

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0002_netposition_participantbalance_settlementattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nettingwindow',
            name='gross_volume',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='tx_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
