# Generated by Django 5.2.16 on 2026-08-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0003_nettingwindow_gross_volume_alter_obligation_tx_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nettingwindow',
            name='gross_volume',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
