# Generated by Django 5.2.16 on 2026-08-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0004_alter_nettingwindow_gross_volume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obligation',
            options={'ordering': ['-timestamp', 'tx_id'], 'verbose_name': 'obligation', 'verbose_name_plural': 'obligations'},
        ),
        migrations.AlterField(
            model_name='obligation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('netted', 'Netted')], default='pending', max_length=10),
        ),
    ]
